Repository expressjs/expressjs.com, pull requests merged in 2024-07, with the labels that each got.

#1538 doc: update snippet to do a proper comparison
  en/advanced/best-practice-security.md
Labels: requires-translation-fr, requires-translation-es, requires-translation-it, requires-translation-ja, requires-translation-ko, requires-translation-pt-br, requires-translation-ru, requires-translation-sk, requires-translation-th, requires-translation-tr, requires-translation-uk, requires-translation-uz, requires-translation-zh-cn, requires-translation-zh-tw

#1519 Express Blog
  _config.yml
  _includes/blog/posts-menu.md
  _includes/blog/tags-menu.md
  _includes/header/header-en.html
  _layouts/post.html
  _posts/2024-07-16-welcome-post.md
  css/dark-theme.css
  css/style.css
  en/blog/posts.md
  en/blog/write-post.md
  images/blogger.jpg
  js/app.js
Labels: blog

#1544 Add link to issue 1500, minor rewording
  _posts/2024-07-16-welcome-post.md
  en/blog/write-post.md
Labels: requires-translation-fr, requires-translation-es, requires-translation-it, requires-translation-ja, requires-translation-ko, requires-translation-pt-br, requires-translation-ru, requires-translation-sk, requires-translation-th, requires-translation-tr, requires-translation-uk, requires-translation-uz, requires-translation-zh-cn, requires-translation-zh-tw, requires-translation-id
