Repository expressjs/expressjs.com, pull requests merged in 2024-10, with the labels that each got.

#1599 Remove confusing note from the 4x documentation
  _includes/api/en/4x/express.static.md
Labels: 4.x

#1610 Update migration guide
  en/guide/migrating-5.md
Labels: 5.x

#1657 blog: Express.js Security Audit - A Milestone Achievement
  _posts/2024-10-22-security-audit-milestone-achievement.md
Labels: blog
