Repository expressjs/expressjs.com, pull requests merged in 2024-09, with the labels that each got.

#1582 mentioned the mergeParams in the routing file.
  en/guide/routing.md
Labels: doc

#1369 Replace fast_star paths with path patterns
  _includes/api/en/5x/app-all.md
  _includes/api/en/5x/router-all.md
Labels: pr, 5.x

#1588 "Using template engines": Remove outdated info and broken links
  en/guide/using-template-engines.md
Labels: requires-translation-fr, requires-translation-es, requires-translation-it, requires-translation-ja, requires-translation-ko, requires-translation-pt-br, requires-translation-ru, requires-translation-sk, requires-translation-th, requires-translation-tr, requires-translation-uk, requires-translation-uz, requires-translation-zh-cn, requires-translation-zh-tw, requires-translation-id

#1609 docs: update community page
  en/resources/community.md
  id/resources/community.md
  pt-br/resources/community.md
  th/resources/community.md
  tr/resources/community.md
Labels: requires-translation-fr, requires-translation-es, requires-translation-it, requires-translation-ja, requires-translation-ko, requires-translation-ru, requires-translation-sk, requires-translation-uk, requires-translation-uz, requires-translation-zh-cn, requires-translation-zh-tw

#1603 v5 is now released
  _includes/header/header-en.html
  _includes/header/header-id.html
  en/support/index.md
Labels: 5.x
