Repository expressjs/expressjs.com, pull requests merged in 2024-05, with the labels that each got.

#1515 Docs: Clarify inheritance behaviour of router params callbacks
  _includes/api/en/4x/app-param.md
  _includes/api/en/4x/router-param.md
  _includes/api/en/5x/app-param.md
  _includes/api/en/5x/router-param.md
Labels: requires-translation-fr, requires-translation-es, requires-translation-en, requires-translation-it, requires-translation-ja, requires-translation-ko, requires-translation-pt-br, requires-translation-ru, requires-translation-sk, requires-translation-th, requires-translation-tr, requires-translation-uk, requires-translation-uz, requires-translation-zh-cn, requires-translation-zh-tw

#1425 Update "query parser" default value in 5.x
  _includes/api/en/5x/app-settings.md
Labels: 5.x, needs tech review

#1502 fix nav links do not reappear after resizing
  css/style.css
  js/app.js
Labels: pr, UI
