Repository expressjs/expressjs.com, pull requests merged in 2025-03, with the labels that each got.

#1811 Do not enforce Ruby version
  .github/workflows/ci.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: enhancement, build

#1812 ci: remove CI on review submission
  .github/workflows/ci.yml
Labels: build

#1730 📄 update license to `CC BY 4.0`
  LICENSE.md
Labels: tc agenda

#1835 docs: add deprecation note for 'back' redirect in res-redirect.md and res-location.md v4
  _includes/api/en/4x/res-location.md
  _includes/api/en/4x/res-redirect.md
  _includes/api/en/5x/res-location.md
  _includes/api/en/5x/res-redirect.md
Labels: docs, 5.x, 4.x

#1849 feat(blog): 5.1.0 release blog
  _posts/2025-03-31-v5-1-latest-release.md
  css/style.css
Labels: blog

#1850 docs(changelog): update changelog for 5.1.0 release
  en/changelog/index.md
Labels: docs, 5.x
