Repository expressjs/expressjs.com, pull requests merged in 2025-02, with the labels that each got.

#1765 fix indonesia support
  _includes/header/header-id.html
  id/support/index.md
Labels: i18n

#1695 feat: add language picker
  _data/languages.yml
  _includes/footer/footer-en.html
  _includes/footer/footer-id.html
  _includes/header/header-de.html
  _includes/header/header-en.html
  _includes/header/header-es.html
  _includes/header/header-fr.html
  _includes/header/header-id.html
  _includes/header/header-it.html
  _includes/header/header-ja.html
  _includes/header/header-ko.html
  _includes/header/header-pt-br.html
  _includes/header/header-ru.html
  _includes/header/header-sk.html
  _includes/header/header-th.html
  _includes/header/header-tr.html
  _includes/header/header-uk.html
  _includes/header/header-uz.html
  _includes/header/header-zh-cn.html
  _includes/header/header-zh-tw.html
  _includes/language-picker-mobile.html
  _includes/language-picker.html
  css/style.css
  js/app.js
  js/menu.js
Labels: design, i18n

#1766 Added bluesky icon and link in all footers
  _includes/footer/footer-de.html
  _includes/footer/footer-en.html
  _includes/footer/footer-es.html
  _includes/footer/footer-fr.html
  _includes/footer/footer-id.html
  _includes/footer/footer-it.html
  _includes/footer/footer-ja.html
  _includes/footer/footer-ko.html
  _includes/footer/footer-pt-br.html
  _includes/footer/footer-ru.html
  _includes/footer/footer-sk.html
  _includes/footer/footer-th.html
  _includes/footer/footer-tr.html
  _includes/footer/footer-uk.html
  _includes/footer/footer-uz.html
  _includes/footer/footer-zh-cn.html
  _includes/footer/footer-zh-tw.html
  _includes/icons/bluesky.svg
Labels: design, i18n

#1773 fix code padding
  css/style.css
Labels: bug, design

#1783 docs: update documentation for res.type()
  _includes/api/en/4x/res-type.md
  _includes/api/en/5x/res-type.md
  en/guide/migrating-5.md
Labels: docs, 5.x, 4.x

#1778 Update API includes to use English language paths
  en/3x/api.md
  en/4x/api.md
  en/5x/api.md
Labels: 3.x, 5.x, i18n, 4.x

#1742 Design system
  _includes/blog/tags-menu.md
  _includes/head.html
  _layouts/home.html
  css/dark-theme.css
  css/langs/de.css
  css/langs/en.css
  css/langs/es.css
  css/langs/fr.css
  css/langs/id.css
  css/langs/it.css
  css/langs/ja.css
  css/langs/ko.css
  css/langs/pt-br.css
  css/langs/ru.css
  css/langs/sk.css
  css/langs/th.css
  css/langs/tr.css
  css/langs/uk.css
  css/langs/uz.css
  css/langs/zh-cn.css
  css/langs/zh-tw.css
  css/style.css
  css/themes/dark-theme.css
  css/variables.css
  en/blog/write-post.md
  js/theme.js
Labels: design, a11y / accessibility, maintenance

#1781 enable incremental build for local server
  Makefile
Labels: maintenance, build

#1679 Update production best practices
  en/advanced/best-practice-performance.md
Labels: docs, needs tech review

#1790 Update "Use helmet" section
  en/advanced/best-practice-security.md
Labels: docs, fast track

#1767 ci: deploy website with github actions
  .github/workflows/deploy.yml
  _config.yml
Labels: maintenance, build

#1791 feat: add configuration to display the announcements
  _config.yml
  _data/en/general.yml
  index.md
Labels: design, build, fast track

#1797 accessibility issue fix for level one heading and its order
  css/langs/th.css
  css/style.css
  de/index.md
  es/index.md
  fr/index.md
  id/index.md
  index.md
  it/index.md
  ja/index.md
  ko/index.md
  pt-br/index.md
  ru/index.md
  sk/index.md
  th/index.md
  tr/index.md
  uk/index.md
  uz/index.md
  zh-cn/index.md
  zh-tw/index.md
Labels: a11y / accessibility

#1796 fix accessibility issue for text distinguishable links
  css/style.css
  de/index.md
  de/support/index.md
  en/support/index.md
  es/index.md
  es/support/index.md
  fr/index.md
  fr/support/index.md
  id/support/index.md
  index.md
  it/index.md
  it/support/index.md
  ja/index.md
  ja/support/index.md
  ko/support/index.md
  pt-br/support/index.md
  ru/index.md
  ru/support/index.md
  sk/support/index.md
  th/support/index.md
  tr/support/index.md
  uk/support/index.md
  uz/support/index.md
  zh-cn/support/index.md
  zh-tw/index.md
  zh-tw/support/index.md
Labels: a11y / accessibility

#1802 fix accessibility issue for iframe accessible name
  de/index.md
  es/index.md
  fr/index.md
  id/index.md
  it/index.md
  ja/index.md
  ru/index.md
  sk/index.md
  th/index.md
  tr/index.md
  uk/index.md
  uz/index.md
  zh-cn/index.md
  zh-tw/index.md
Labels: a11y / accessibility

#1806 fix: update middleware documentation
  en/resources/middleware.md
Labels: docs

#1809 fix accessibility issue related to image alt text
  de/guide/writing-middleware.md
  en/guide/writing-middleware.md
  en/resources/community.md
  es/guide/writing-middleware.md
  es/resources/community.md
  fr/guide/writing-middleware.md
  id/guide/writing-middleware.md
  it/guide/writing-middleware.md
  ja/guide/writing-middleware.md
  ko/guide/writing-middleware.md
  pt-br/guide/writing-middleware.md
  ru/guide/writing-middleware.md
  sk/guide/writing-middleware.md
  th/guide/writing-middleware.md
  tr/guide/writing-middleware.md
  uk/guide/writing-middleware.md
  uk/resources/community.md
  zh-cn/guide/writing-middleware.md
  zh-tw/guide/writing-middleware.md
Labels: a11y / accessibility

#1818 fix(1815): colour contrast adjusted for comments in code blocks
  css/sintax.css
Labels: a11y / accessibility

#1821 Fix broken links on the middleware page
  en/resources/middleware.md
Labels: fast track
