Repository expressjs/expressjs.com, pull requests merged in 2025-08, with the labels that each got.

#1980 docker: match GH page ruby version
  .ruby-version
  Dockerfile
Labels: build, docker

#1964 chore: ♻️ remove jquery
  _includes/head.html
  _includes/i18n-notice.html
  _layouts/home.html
  _layouts/page.html
  css/style.css
  js/app.js
Labels: maintenance

#1979 ci: remove base_url from crowdin workflows
  .github/workflows/crowdin.yml
  .github/workflows/update-external-docs.yml
  crowdin.yml
Labels: i18n, build

#2001 docs: add option to express.urlencoded middleware documentation
  _includes/api/en/4x/express.urlencoded.md
  _includes/api/en/5x/express.urlencoded.md
Labels: docs, 5.x, 4.x
